name: CI/CD using terraform & AWS

on:
    push:
        branches: 
            - dev

env:
    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY}}
    AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY}}
    DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME}}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

jobs:

    deploy-infra:
        runs-on: ubuntu-latest
        outputs:
            SERVER_PUBLIC_IP: ${{steps.set-ip.outputs.instance_public_ip}}

        steps:

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                    terraform_wrapper: false
                    
            -   name: Terraform init
                id: init        
                run: terraform init
                working-directory: ./terraform

            -   name: Terraform plan
                id: plan
                run: |-
                    terraform plan \
                    -var="private_key=$AWS_SSH_PRIVATE_KEY" \
                    -out=PLAN
                working-directory: ./terraform

            -   name: Terraform apply
                id: apply
                run: terraform apply PLAN 
                working-directory: ./terraform

            -   name: Print
                run: |-
                    echo "$(terraform output -raw public_ip)"
                working-directory: ./terraform

            -   name: Set outputs
                id: set-ip
                run: |-
                    echo "instance_public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
                working-directory: ./terraform
                
    
    deploy-app:
        runs-on: ubuntu-latest
        needs: deploy-infra

        steps:

            -   name: Checkout
                uses: actions/checkout@v4 

            -   name: Set ip to env
                run: echo SERVER_PUBLIC_IP=${{needs.deploy-infra.outputs.SERVER_PUBLIC_IP}} >> $GITHUB_ENV

            -   name: Login to docker hub
                run: docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD

            -   name: Build & push docker image
                run: |-
                    docker build -t ${{env.DOCKER_USER_NAME}}/node-app:${{github.sha}} .
                    docker push ${{env.DOCKER_USER_NAME}}/node-app:${{github.sha}}
                working-directory: ./nodeapp

            -   name: Debug IP
                run: echo "Server IP is $SERVER_PUBLIC_IP"

            -   name: Deploy docker imge to Ec2
                uses: appleboy/ssh-action@master
                with:
                    host: ${{env.SERVER_PUBLIC_IP}} 
                    username: ubuntu
                    key: ${{env.AWS_SSH_PRIVATE_KEY}}
                    script: |-
                        sudo apt update 
                        sudo apt install docker.io -y
                        sudo docker stop node-app || true
                        sudo docker rm node-app || true
                        sudo docker pull ${{env.DOCKER_USER_NAME}}/node-app:${{github.sha}}
                        sudo docker run -d -p 80:8080 --name node-app ${{env.DOCKER_USER_NAME}}/node-app:${{github.sha}}